-- Procedimientos almacenados
-- 1. Registrar un nuevo camper con toda su información personal y estado inicial.
-- 2. Actualizar el estado de un camper luego de completar el proceso de ingreso.
-- 3. Procesar la inscripción de un camper a una ruta específica.
-- 4. Registrar una evaluación completa (teórica, práctica y quizzes) para un camper.
-- 5. Calcular y registrar automáticamente la nota final de un módulo.
-- 6. Asignar campers aprobados a una ruta de acuerdo con la disponibilidad del área.
-- 7. Asignar un trainer a una ruta y área específica, validando el horario.
-- 8. Registrar una nueva ruta con sus módulos y SGDB asociados.
-- 9. Registrar una nueva área de entrenamiento con su capacidad y horarios.
-- 10. Consultar disponibilidad de horario en un área determinada.
-- 11. Reasignar a un camper a otra ruta en caso de bajo rendimiento.
-- 12. Cambiar el estado de un camper a “Graduado” al finalizar todos los módulos.
-- 13. Consultar y exportar todos los datos de rendimiento de un camper.
-- 14. Registrar la asistencia a clases por área y horario.
-- 15. Generar reporte mensual de notas por ruta.
-- 16. Validar y registrar la asignación de un salón a una ruta sin exceder la capacidad.
-- 17. Registrar cambio de horario de un trainer.
-- 18. Eliminar la inscripción de un camper a una ruta (en caso de retiro).
-- 19. Recalcular el estado de todos los campers según su rendimiento acumulado.
-- 20. Asignar horarios automáticamente a trainers disponibles según sus áreas