-- Funciones
-- 1. Calcular el promedio ponderado de evaluaciones de un camper.
-- 2. Determinar si un camper aprueba o no un módulo específico.
-- 3. Evaluar el nivel de riesgo de un camper según su rendimiento promedio.
-- 4. Obtener el total de campers asignados a una ruta específica.
-- 5. Consultar la cantidad de módulos que ha aprobado un camper.
-- 6. Validar si hay cupos disponibles en una determinada área.
-- 7. Calcular el porcentaje de ocupación de un área de entrenamiento.
-- 8. Determinar la nota más alta obtenida en un módulo.
-- 9. Calcular la tasa de aprobación de una ruta.
-- 10. Verificar si un trainer tiene horario disponible.
-- 11. Obtener el promedio de notas por ruta.
-- 12. Calcular cuántas rutas tiene asignadas un trainer.
-- 13. Verificar si un camper puede ser graduado.
-- 14. Obtener el estado actual de un camper en función de sus evaluaciones.
-- 15. Calcular la carga horaria semanal de un trainer.
-- 16. Determinar si una ruta tiene módulos pendientes por evaluación.
-- 17. Calcular el promedio general del programa.
-- 18. Verificar si un horario choca con otros entrenadores en el área.
-- 19. Calcular cuántos campers están en riesgo en una ruta específica.
-- 20. Consultar el número de módulos evaluados por un camper.